name: CI

on:
  release:
    types: [created]

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install
        run: npm ci
      - name: npm run build
        run: npm run build
      - name: npm run zip
        run: npm run zip
      - name: Upload files to GitHub release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'dist_zip/*.zip'
